//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce_shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Decentralized
    {
        public int idStaff { get; set; }
        public int idFunction { get; set; }
        public string Comment { get; set; }
    
        public virtual Function Function { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
