//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce_shop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int ID { get; set; }
        [DisplayName("Tên Tài Khoản")]
        [Required(ErrorMessage ="Nhập tài khoản bạn nhé")]
        public string Username { get; set; }
        [DisplayName("Mật Khẩu")]
        [Required(ErrorMessage = "Nhập mật khẩu bạn nhé")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [DisplayName("Email")]
        [Required(ErrorMessage = "Nhập email bạn nhé")]
        public string Email { get; set; }
        [DisplayName("Họ và Tên")]
        [Required(ErrorMessage = "Nhập Họ và tên bạn nhé")]
        public string HoVaTen { get; set; }
        [DisplayName("Số điện thoại")]
        [Required(ErrorMessage = "Nhập số điện thoại bạn nhé")]
        public string SoDienThoai { get; set; }
        [DisplayName("Nhập lại mật khẩu")]
        [Required(ErrorMessage = "Nhập lại mật khẩu không đúng")]
        [DataType(DataType.Password)]
        [Compare("Password")]
        public string RePassword { get; set; }
        public string LoginErrorMessage { get; set; }
    }
}
